name: TypeDocをGitHub Pagesにデプロイする

on: [push] # git push したときに実行する

jobs:
  typedoc:
    name: TypeDoc
    runs-on: ubuntu-latest # Ubuntuの最新版を実行環境とする
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v1
        with:
          node-version: '12' # Node 12を使う
      - name: Dependencies
        run: yarn --frozen-lockfile --ignore-optional
      - name: TypeDoc
        run: npx typedoc --includeVersion --out reference src
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./docs
